# Dockerfile for React client

# Build react client
FROM node:16.13

# Working directory be app
WORKDIR /usr/src/app

# COPY package*.json ./
COPY . /usr/src/app

# copy local files to app folder
# COPY ./src ./src
# COPY webpack.config.js .

###  Installing dependencies

RUN npm install --silent
RUN npm run build

# ENTRYPOINT ["node", "server/server.js"]

EXPOSE 3000
# ENTRYPOINT ["node", "./server/server"]
# ENTRYPOINT node ./build/bundle.js

CMD ["npx", "ts-node", "./server/server"]